### PR TITLE
Hotfix/create delete column template

### PR DESCRIPTION
**Pull request by kYann**

### CODE REVIEW

**Comment by virneo** [comment]
Can we get this merged? Also I will be happy to update the nuget package as well if @jeffreyabecker doesn't want to manage this anymore.

**Comment by jeffreyabecker** [comment]
I'm happy to hand off upkeep of this project. Could you provide a couple
links on how?

**Comment by virneo** [comment]
Well giving admin privileges on git repo is easy, possibly also transferring it to another user is fine. The main problem is the Nuget.org account which in your case must be an individual account. The only way is to make your account an organization account, and then add me in the organization.
https://docs.microsoft.com/en-us/nuget/nuget-org/organizations-on-nuget-org. 
That way both of us will be able to manage the package and I will be able to add more people to the organization provided I have the rights.

**Comment by virneo** [comment]
@jeffreyabecker Please make me a collaborator on this repository, so that I can merge the PR in a new version. Regarding nuget package, we can release this package with a new name like FluentMigrator.Nhibernate2 using a separate account. This way you won't have to make any change in your nuget account. I would handle all of it, if you make me a collaborator on this repo. Thanks :)

**Comment by virneo** [comment]
Thanks a lot :).

**Pull request merged**
